############################################################
# Dockerfile to build clients-data-service-app container image
# Based on docker.dos.softlab.ru/rshb/efr/communication-systems/library/jboss-wildfly:10.1.01-cli
############################################################

# Use base wildfly 10.1.0 image as the base
FROM docker.dos.softlab.ru/rshb/efr/communication-systems/ibm/wsl:0.0.1-ext

# Deploy app
ADD ./target/*.war /config/dropins/